### ISSUE TITLE
emoticons missing from 3.6.1

### ISSUE THREAD

**Issue by gothmog123** [slp/Telegram-FOSS#83]
Hi I just upgraded to Telegram 3.6.1 from F-Droid running on Cyanogenmod and emoticons are invisible (there is a blank space where they should be).

Would appreciate any help - thank you very much.

**Comment by Roboe** [comment]
Same here. Only fails in conversation view; works on preview in conversations list, message input box and emoji menu as expected (native emojis)

**Comment by c33s** [comment]
see https://github.com/slp/Telegram-FOSS/issues/81

**Comment by PanderMusubi** [comment]
Same here, I use to have these emoji http://www.emoji-cheat-sheet.com/ but see not only these emoji https://40.media.tumblr.com/91857e013d691d4bd1db4de90bf20fa6/tumblr_nxq53cFdYm1sztyb3o1_1280.png with a lot missing

**Comment by Roboe** [comment]
Fixed on version 3.6.1a (ebd09f9), already on F-Droid. 

@PanderMusubi, your issue is a different one. Apple's emojis were removed for licensing issues. See #35 and also #53

**Comment by PanderMusubi** [comment]
@Roboe After upgrading to 3.6.1 I saw the Noto emoji, but that is probably because they were already available on my system, the native set. With 3.6.1a I see the same. Is it correct that several Noto emoji are still missing?

**Comment by PanderMusubi** [comment]
![screenshot_2016-03-10-15-55-00](https://cloud.githubusercontent.com/assets/198964/13673279/9d83d76a-e6d8-11e5-82b3-d5ee670b0e28.png)

**Comment by Bubu** [comment]
That is expected, I updated the emoji code so that you can select the same emoji as upstream Telegram and in the same places.
Most of them should be present on Android 6.0.1 but quite a few are missing before that.

I plan to implement an option for using the emojiOne set for all older devices in a later release. See #50

**Comment by PanderMusubi** [comment]
OK, so it is as intended. Looking forward to when the others are supported. Two questions. Can you backport only the missing emoji from Android 6.0.1 inside Telegram-FOSS for older devices? If Android 6.0.1 is still missing some, is there an issues for that to chase or contribute to?

**Comment by Bubu** [comment]
@PanderMusubi If you have root you can do this: http://blog.hroyer.com/post/134741931803/install-the-new-android-601-emojis-on-your
But his is not something Telegram should do.

**Comment by PanderMusubi** [comment]
No root, so I will await 6.0.1. Thanks for the background info.

**Comment by PanderMusubi** [comment]
http://m.slashdot.org/story/309723
